INSERT INTO Guest (name, second_name, alcohol, spice, color, music) VALUES
    ('Jane', 'Smith', 'Vodka', 'Spicy', 'Red', 'Pop'),
    ('Alice', 'Johnson', 'Beer', 'Mild', 'Green', 'Jazz'),
    ('Bob', 'Williams', 'Wine', 'Hot', 'Purple', 'Classical'),
    ('Eva', 'Anderson', 'Rum', 'Mild', 'Yellow', 'Blues'),
    ('Chris', 'Brown', 'Tequila', 'Medium', 'Orange', 'Country'),
    ('Olivia', 'Davis', 'Gin', 'Spicy', 'Pink', 'Electronic'),
    ('Michael', 'Taylor', 'Scotch', 'Hot', 'Black', 'Hip Hop'),
    ('Emily', 'Miller', 'Bourbon', 'Medium', 'Blue', 'Rock'),
    ('Jacob', 'Robinson', 'Whiskey', 'Mild', 'White', 'Reggae'),
    ('Isabella', 'Jones', 'Vodka', 'Mild', 'Red', 'Pop'),
    ('William', 'White', 'Beer', 'Spicy', 'Green', 'Jazz'),
    ('Sophia', 'Harris', 'Wine', 'Hot', 'Purple', 'Classical'),
    ('Daniel', 'Martin', 'Rum', 'Mild', 'Yellow', 'Blues'),
    ('Alexander', 'Thompson', 'Tequila', 'Medium', 'Orange', 'Country'),
    ('Emma', 'Garcia', 'Gin', 'Spicy', 'Pink', 'Electronic'),
    ('Joseph', 'Martinez', 'Scotch', 'Hot', 'Black', 'Hip Hop'),
    ('Ava', 'Robinson', 'Bourbon', 'Medium', 'Blue', 'Rock'),
    ('Elijah', 'Clark', 'Whiskey', 'Mild', 'White', 'Reggae'),
    ('Mia', 'Lopez', 'Vodka', 'Spicy', 'Red', 'Pop'),
    ('Benjamin', 'Miller', 'Beer', 'Mild', 'Green', 'Jazz'),
    ('Charlotte', 'Wilson', 'Wine', 'Hot', 'Purple', 'Classical'),
    ('Liam', 'Taylor', 'Rum', 'Mild', 'Yellow', 'Blues'),
    ('Noah', 'Anderson', 'Tequila', 'Medium', 'Orange', 'Country'),
    ('Abigail', 'Thomas', 'Gin', 'Spicy', 'Pink', 'Electronic'),
    ('Olivia', 'Jackson', 'Scotch', 'Hot', 'Black', 'Hip Hop'),
    ('William', 'White', 'Bourbon', 'Medium', 'Blue', 'Rock'),
    ('Elijah', 'Harris', 'Whiskey', 'Mild', 'White', 'Reggae');

INSERT INTO Room (id, floor, color, beds, price) VALUES
    (11, 1, 'Red', 1, 100),
    (12, 1, 'Green', 2, 200),
    (13, 1, 'Blue', 3, 300),
    (14, 2, 'Red', 1, 100),
    (15, 2, 'Green', 2, 200),
    (21, 2, 'Blue', 3, 300),
    (22, 2, 'Red', 1, 100),
    (23, 2, 'Green', 2, 200),
    (24, 2, 'Blue', 3, 300),
    (25, 2, 'Red', 1, 100),
    (31, 3, 'Red', 1, 100),
    (32, 3, 'Green', 2, 200),
    (33, 3, 'Blue', 3, 300),
    (34, 3, 'Red', 1, 100),
    (35, 3, 'Green', 2, 200);
